spring:
 datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/phototab
    username: root
    password: admin

 jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
 output:
   ansi:
     enabled: always
server:
  port: 8080
serverSecret: Hjs#n)nq%sd*(mm@ef&dds




